import Head from "next/head";
import { Inter } from "next/font/google";
import { useState } from "react";
import { GetServerSideProps } from "next";
import "semantic-ui-css/semantic.min.css";
import { Loader } from "semantic-ui-react";

const inter = Inter({ subsets: ["latin"] });

interface SearchCatImage {
  id: string;
  url: string;
  width: number;
  height: number;
}

interface indexPageProps {
  initialCatImageUrl: string;
}

const fetchCatImage = async (): Promise<SearchCatImage> => {
  const res = await fetch("https://api.thecatapi.com/v1/images/search");
  const result = await res.json();
  return result[0];
};

//SSR
export const getServerSideProps: GetServerSideProps<
  indexPageProps
> = async () => {
  const catImage = await fetchCatImage();
  return {
    props: {
      initialCatImageUrl: catImage.url,
    },
  };
};

export default function Home({ initialCatImageUrl }: indexPageProps) {
  const [catImageUrl, setCatImageUrl] = useState(initialCatImageUrl);
  const [isLoading, setIsLoading] = useState(false);

  const handleClick = async () => {
    setIsLoading(true);
    const catImage = await fetchCatImage();
    setCatImageUrl(catImage.url);
    setIsLoading(false);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
          }}
        >
          <h1>猫画像アプリ</h1>
          {isLoading ? (
            <Loader active />
          ) : (
            <img
              src={catImageUrl}
              style={{
                width: "400px",
                height: "300px",
                objectFit: "cover",
              }}
            />
          )}
          <button
            style={{
              display: "block",
              marginTop: "20px",
            }}
            onClick={handleClick}
          >
            今日のねこ
          </button>
        </div>
      </main>
    </>
  );
}
